language: ruby
addons:
  chrome: stable
cache: bundler
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem update --system
install: bundle install
script:
  - bundle exec rubocop
  - bundle exec rspec
