language: ruby
rvm:
  - 2.3.0
before_script:
  - gem install rails --no-ri --no-rdoc
  - cd ..
  - boxcar/bin/gen_interactive_app
  - boxcar/bin/gen_api_only_app
  - boxcar/bin/gen_api_admin_app
script:
  - rubocop ./boxcar
  - cd interactive_app
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec rake cucumber
  - cd ..
  - cd api_only_app
  - bundle exec rubocop
  - bundle exec rspec
  - cd ..
  - cd api_admin_app
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec rake cucumber
